"""
Regenerate the paper's result tables from the metrics files on disk.

Hand-copying numbers into LaTeX is how papers end up with tables that disagree
with their own artefacts. This reads every metrics.json produced by
tasks/evaluate.py and emits both a readable summary and LaTeX table bodies.

Usage:
    python tasks/make_paper_tables.py                 # print
    python tasks/make_paper_tables.py --tex paper/tables.tex
"""
import argparse
import glob
import json
import os

import numpy as np

# metric -> (label, higher_is_better, decimals)
METRICS = {
    'color_error': ('Color error', False, 4),
    'lr_psnr':     ('LR-PSNR',     True,  3),
    'psnr':        ('PSNR',        True,  3),
    'ssim':        ('SSIM',        True,  4),
    'lpips':       ('LPIPS',       False, 4),
    'fid':         ('FID',         False, 2),
}

# Runs contributed from outside this machine (e.g. the user's Colab session) are
# listed explicitly so the seed count in the paper matches what actually exists.
EXTERNAL = {
    'celeba_baseline': [
        {'source': 'colab', 'psnr': 25.093977, 'ssim': 0.816666, 'lpips': 0.043768,
         'lr_psnr': 45.144927, 'color_error': 0.387789, 'fid': 65.543493},
    ],
    'celeba_cc': [
        {'source': 'colab', 'psnr': 25.112910, 'ssim': 0.816397, 'lpips': 0.042142,
         'lr_psnr': 45.709536, 'color_error': 0.206092, 'fid': 66.080698},
    ],
}

GROUPS = {
    'celeba_baseline': ['diffsr_celebA_small_baseline', 'diffsr_celebA_s2024_baseline'],
    'celeba_cc':       ['diffsr_celebA_small_cc',       'diffsr_celebA_s2024_cc'],
    'celeba_cc_snr':   ['diffsr_celebA_small_cc_snr'],
    'div2k_baseline':  ['diffsr_div2k_small_baseline'],
    'div2k_cc':        ['diffsr_div2k_small_cc'],
}


def load(exp):
    paths = sorted(glob.glob(f'checkpoints/{exp}/results_*/metrics.json'))
    if not paths:
        return None
    with open(paths[-1]) as f:
        m = json.load(f)
    m['source'] = exp
    return m


def collect(group):
    runs = [r for r in (load(e) for e in GROUPS[group]) if r is not None]
    runs += EXTERNAL.get(group, [])
    return runs


def stats(runs, key):
    vals = [r[key] for r in runs if key in r]
    if not vals:
        return None
    a = np.array(vals, dtype=float)
    return a.mean(), (a.std(ddof=1) if len(a) > 1 else 0.0), len(a)


def fmt(group, key):
    s = stats(collect(group), key)
    if s is None:
        return 'n/a'
    mean, sd, n = s
    d = METRICS[key][2]
    return f'{mean:.{d}f}' + (f' $\\pm$ {sd:.{d}f}' if n > 1 else '')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tex', default=None)
    args = ap.parse_args()

    lines = []
    for title, gb, gc in [('CelebA 4x', 'celeba_baseline', 'celeba_cc'),
                          ('DIV2K 4x', 'div2k_baseline', 'div2k_cc')]:
        rb, rc = collect(gb), collect(gc)
        if not rb or not rc:
            lines.append(f'\n== {title}: incomplete ({len(rb)} baseline, {len(rc)} cc runs) ==')
            continue
        lines.append(f'\n== {title}  (n={len(rb)} baseline, n={len(rc)} cc) ==')
        lines.append(f"{'metric':<12} {'baseline':>22} {'CC-ResDiff':>22} {'delta':>12}")
        for k, (label, higher, d) in METRICS.items():
            sb, sc = stats(rb, k), stats(rc, k)
            if sb is None or sc is None:
                continue
            delta = sc[0] - sb[0]
            good = (delta > 0) if higher else (delta < 0)
            lines.append(f'{label:<12} {fmt(gb, k):>22} {fmt(gc, k):>22} '
                         f"{delta:>+11.{d}f} {'better' if good else 'worse'}")

    snr = collect('celeba_cc_snr')
    if snr:
        lines.append(f'\n== SNR-weighted GCC (n={len(snr)}) ==')
        for k, (label, _, d) in METRICS.items():
            s = stats(snr, k)
            if s:
                lines.append(f'{label:<12} {s[0]:.{d}f}')
    else:
        lines.append('\n== SNR-weighted GCC: not yet evaluated ==')

    out = '\n'.join(lines)
    print(out)
    if args.tex:
        os.makedirs(os.path.dirname(args.tex) or '.', exist_ok=True)
        with open(args.tex, 'w') as f:
            f.write('% auto-generated by tasks/make_paper_tables.py\n')
            f.write('\n'.join('% ' + l for l in lines) + '\n')
        print(f'\nWrote {args.tex}')


if __name__ == '__main__':
    main()
